# Generated by Django 3.2.19 on 2023-07-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('acceptable', models.BooleanField(default=False)),
                ('good', models.BooleanField(default=False)),
                ('excellent', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('storage_size', models.CharField(max_length=50)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('label', models.CharField(max_length=50)),
                ('cpu_brand', models.CharField(max_length=50)),
                ('cpu_name', models.CharField(max_length=50)),
                ('ssd', models.BooleanField(default=False)),
                ('storage_size', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('cpu_variant', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=50)),
                ('cores', models.PositiveIntegerField(choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12)])),
                ('os', models.CharField(max_length=50)),
                ('usb', models.CharField(max_length=50)),
                ('hdmi', models.CharField(max_length=50)),
                ('touchscreen', models.BooleanField(default=False)),
                ('screen_size', models.PositiveIntegerField(choices=[(11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17)])),
                ('dimensions', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('finger_print_sensor', models.BooleanField(default=False)),
                ('keyboard', models.CharField(max_length=50)),
                ('backlit', models.BooleanField(default=False)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('sim', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('storage_size', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resolution', models.CharField(max_length=50)),
                ('camera_front', models.CharField(max_length=50)),
                ('camera_rear', models.CharField(max_length=50)),
                ('os', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS')], max_length=50)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Smartwatch',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('connectivity', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=50)),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resolution', models.CharField(max_length=50)),
                ('water_resistance', models.CharField(max_length=50)),
                ('heart_rate_monitor', models.BooleanField(default=False)),
                ('gps', models.BooleanField(default=False)),
                ('os', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Smartwatches',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptable_amount', models.PositiveIntegerField(default=0)),
                ('good_amount', models.PositiveIntegerField(default=0)),
                ('excellent_amount', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
