# Generated by Django 3.2.19 on 2023-07-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='acceptable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='excellent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='good',
        ),
    ]
