# Generated by Django 3.2.19 on 2023-06-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_laptop_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='ssd',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=254),
        ),
    ]
