# Generated by Django 3.2.19 on 2023-06-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_laptop_ssd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('series', models.CharField(max_length=254)),
                ('model', models.CharField(max_length=254)),
                ('sim', models.CharField(max_length=254)),
                ('cpu', models.CharField(max_length=254)),
                ('ram', models.CharField(max_length=254)),
                ('storage_size', models.CharField(max_length=254)),
                ('battery', models.CharField(max_length=254)),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resolution', models.CharField(max_length=254)),
                ('camera_front', models.CharField(max_length=254)),
                ('camera_rear', models.CharField(max_length=254)),
                ('os', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS')], max_length=254)),
                ('color', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
