# Generated by Django 3.2.19 on 2023-06-23 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_smartwatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Microsoft', 'Microsoft'), ('Sony', 'Sony'), ('Nintendo', 'Nintendo')], max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('series', models.CharField(max_length=254)),
                ('model', models.CharField(max_length=254)),
                ('storage_size', models.CharField(max_length=254)),
                ('color', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
