# Generated by Django 3.2.19 on 2023-06-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_console'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
